### ISSUE TITLE
issue while generating 

### ISSUE THREAD

**Issue by BlankSama** [toshikiochiai/NPVAE#2]
Hi,

iam facing the following issue :
Traceback (most recent call last):
  File "generate.py", line 167, in <module>
    main(args)
  File "generate.py", line 39, in main
    model.load_state_dict(new_state_dict)
  File "/home/administrator/anaconda3/envs/npvae_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Chem_VAE:
        size mismatch for label_pred3.weight: copying a param with shape torch.Size([13681, 2048]) from checkpoint, the shape in current model is torch.Size([8658, 2048]).
        size mismatch for label_pred3.bias: copying a param with shape torch.Size([13681]) from checkpoint, the shape in current model is torch.Size([8658]).
        size mismatch for label_pred1_3.weight: copying a param with shape torch.Size([13681, 2048]) from checkpoint, the shape in current model is torch.Size([8658, 2048]).
        size mismatch for label_pred1_3.bias: copying a param with shape torch.Size([13681]) from checkpoint, the shape in current model is torch.Size([8658]).

Please help

**Comment by YOtani11517** [comment]
I have the same problem, too.
